import Foundation

enum UnitMap {
    private static let units: [String: Dimension] = [
        // Length
        "mm": UnitLength.millimeters,
        "millimeter": UnitLength.millimeters,
        "millimeters": UnitLength.millimeters,
        "cm": UnitLength.centimeters,
        "centimeter": UnitLength.centimeters,
        "centimeters": UnitLength.centimeters,
        "m": UnitLength.meters,
        "meter": UnitLength.meters,
        "meters": UnitLength.meters,
        "km": UnitLength.kilometers,
        "kilometer": UnitLength.kilometers,
        "kilometers": UnitLength.kilometers,
        "in": UnitLength.inches,
        "inch": UnitLength.inches,
        "inches": UnitLength.inches,
        "ft": UnitLength.feet,
        "foot": UnitLength.feet,
        "feet": UnitLength.feet,
        "yd": UnitLength.yards,
        "yard": UnitLength.yards,
        "yards": UnitLength.yards,
        "mi": UnitLength.miles,
        "mile": UnitLength.miles,
        "miles": UnitLength.miles,

        // Mass
        "mg": UnitMass.milligrams,
        "milligram": UnitMass.milligrams,
        "milligrams": UnitMass.milligrams,
        "g": UnitMass.grams,
        "gram": UnitMass.grams,
        "grams": UnitMass.grams,
        "kg": UnitMass.kilograms,
        "kilogram": UnitMass.kilograms,
        "kilograms": UnitMass.kilograms,
        "oz": UnitMass.ounces,
        "ounce": UnitMass.ounces,
        "ounces": UnitMass.ounces,
        "lb": UnitMass.pounds,
        "lbs": UnitMass.pounds,
        "pound": UnitMass.pounds,
        "pounds": UnitMass.pounds,
        "ton": UnitMass.shortTons,
        "tons": UnitMass.shortTons,

        // Volume
        "ml": UnitVolume.milliliters,
        "milliliter": UnitVolume.milliliters,
        "milliliters": UnitVolume.milliliters,
        "l": UnitVolume.liters,
        "liter": UnitVolume.liters,
        "liters": UnitVolume.liters,
        "cup": UnitVolume.cups,
        "cups": UnitVolume.cups,
        "tbsp": UnitVolume.tablespoons,
        "tablespoon": UnitVolume.tablespoons,
        "tablespoons": UnitVolume.tablespoons,
        "tsp": UnitVolume.teaspoons,
        "teaspoon": UnitVolume.teaspoons,
        "teaspoons": UnitVolume.teaspoons,
        "fl oz": UnitVolume.fluidOunces,
        "fluid ounce": UnitVolume.fluidOunces,
        "fluid ounces": UnitVolume.fluidOunces,
        "gal": UnitVolume.gallons,
        "gallon": UnitVolume.gallons,
        "gallons": UnitVolume.gallons,
        "pt": UnitVolume.pints,
        "pint": UnitVolume.pints,
        "pints": UnitVolume.pints,
        "qt": UnitVolume.quarts,
        "quart": UnitVolume.quarts,
        "quarts": UnitVolume.quarts,

        // Temperature
        "c": UnitTemperature.celsius,
        "celsius": UnitTemperature.celsius,
        "f": UnitTemperature.fahrenheit,
        "fahrenheit": UnitTemperature.fahrenheit,
        "k": UnitTemperature.kelvin,
        "kelvin": UnitTemperature.kelvin,

        // Speed
        "mph": UnitSpeed.milesPerHour,
        "kph": UnitSpeed.kilometersPerHour,
        "kmh": UnitSpeed.kilometersPerHour,
        "knot": UnitSpeed.knots,
        "knots": UnitSpeed.knots,

        // Area
        "sq ft": UnitArea.squareFeet,
        "square foot": UnitArea.squareFeet,
        "square feet": UnitArea.squareFeet,
        "sq m": UnitArea.squareMeters,
        "square meter": UnitArea.squareMeters,
        "square meters": UnitArea.squareMeters,
        "acre": UnitArea.acres,
        "acres": UnitArea.acres,
        "hectare": UnitArea.hectares,
        "hectares": UnitArea.hectares,

        // Duration
        "sec": UnitDuration.seconds,
        "second": UnitDuration.seconds,
        "seconds": UnitDuration.seconds,
        "min": UnitDuration.minutes,
        "minute": UnitDuration.minutes,
        "minutes": UnitDuration.minutes,
        "hr": UnitDuration.hours,
        "hour": UnitDuration.hours,
        "hours": UnitDuration.hours,

        // Digital storage
        "byte": UnitInformationStorage.bytes,
        "bytes": UnitInformationStorage.bytes,
        "kb": UnitInformationStorage.kilobytes,
        "kilobyte": UnitInformationStorage.kilobytes,
        "kilobytes": UnitInformationStorage.kilobytes,
        "mb": UnitInformationStorage.megabytes,
        "megabyte": UnitInformationStorage.megabytes,
        "megabytes": UnitInformationStorage.megabytes,
        "gb": UnitInformationStorage.gigabytes,
        "gigabyte": UnitInformationStorage.gigabytes,
        "gigabytes": UnitInformationStorage.gigabytes,
        "tb": UnitInformationStorage.terabytes,
        "terabyte": UnitInformationStorage.terabytes,
        "terabytes": UnitInformationStorage.terabytes,
    ]

    static func unit(for input: String) -> Dimension? {
        units[input.lowercased().trimmingCharacters(in: .whitespaces)]
    }
}
